name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [self-hosted, runner]
    strategy:
      matrix:
        node-version: [22.5.0]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Copy environment file
        run: cp ../../../../.env.frontend .env

      - name: Build
        run: npm run build .

      - name: Restart Nginx
        run: sudo service nginx restart
